"use client";

import { useEffect, useState } from "react";
import FlashcardViewer from "./components/FlashcardViewer";
import QuizMode from "./components/QuizMode";
import { Deck } from "@/lib/types";
import { fetchDecks, generateDeck, deleteDeck as deleteDeckRequest } from "@/lib/api";

type Mode = "flashcards" | "quiz";

export default function Home() {
  const [notes, setNotes] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [decks, setDecks] = useState<Deck[]>([]);
  const [decksLoading, setDecksLoading] = useState(true);
  const [decksError, setDecksError] = useState<string | null>(null);
  const [activeDeckId, setActiveDeckId] = useState<string | null>(null);
  const [mode, setMode] = useState<Mode>("flashcards");

  useEffect(() => {
    let cancelled = false;
    fetchDecks()
      .then((loaded) => {
        if (!cancelled) setDecks(loaded);
      })
      .catch((err) => {
        if (!cancelled) {
          setDecksError(err instanceof Error ? err.message : "Failed to load decks.");
        }
      })
      .finally(() => {
        if (!cancelled) setDecksLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const activeDeck = decks.find((d) => d.id === activeDeckId) ?? null;

  async function handleGenerate() {
    setError(null);
    setLoading(true);
    try {
      const deck = await generateDeck(notes);
      setDecks((prev) => [deck, ...prev]);
      setActiveDeckId(deck.id);
      setMode("flashcards");
      setNotes("");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setLoading(false);
    }
  }

  async function handleDelete(id: string) {
    const previous = decks;
    setDecks((prev) => prev.filter((d) => d.id !== id));
    if (activeDeckId === id) setActiveDeckId(null);
    try {
      await deleteDeckRequest(id);
    } catch (err) {
      setDecks(previous);
      setDecksError(err instanceof Error ? err.message : "Failed to delete deck.");
    }
  }

  return (
    <div className="min-h-screen bg-neutral-50 dark:bg-neutral-950">
      <div className="mx-auto flex max-w-5xl flex-col gap-8 px-6 py-12 sm:px-10">
        <header>
          <h1 className="text-2xl font-semibold">Study Buddy</h1>
          <p className="mt-1 text-sm text-neutral-500">
            Paste your notes, get flashcards and a quiz generated by Claude.
          </p>
        </header>

        <section className="flex flex-col gap-3 rounded-xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900">
          <textarea
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Paste lecture notes, a reading summary, or any study material here..."
            rows={8}
            className="w-full resize-y rounded-md border border-neutral-200 bg-neutral-50 p-3 text-sm outline-none focus:border-neutral-400 dark:border-neutral-700 dark:bg-neutral-950"
          />
          <div className="flex items-center justify-between">
            <p className="text-xs text-neutral-400">{notes.length} characters</p>
            <button
              onClick={handleGenerate}
              disabled={loading || notes.trim().length === 0}
              className="rounded-md bg-neutral-900 px-4 py-2 text-sm text-white disabled:opacity-40 dark:bg-white dark:text-neutral-900"
            >
              {loading ? "Generating..." : "Generate flashcards"}
            </button>
          </div>
          {error && <p className="text-sm text-red-600">{error}</p>}
        </section>

        <div className="grid grid-cols-1 gap-8 md:grid-cols-[220px_1fr]">
          <aside className="flex flex-col gap-2">
            <h2 className="text-xs font-semibold uppercase tracking-wide text-neutral-400">
              Your decks
            </h2>
            {decksError && <p className="text-sm text-red-600">{decksError}</p>}
            {decksLoading && (
              <p className="text-sm text-neutral-400">Loading decks...</p>
            )}
            {!decksLoading && !decksError && decks.length === 0 && (
              <p className="text-sm text-neutral-400">No decks yet.</p>
            )}
            {decks.map((deck) => (
              <div
                key={deck.id}
                className={[
                  "group flex items-center justify-between rounded-md px-3 py-2 text-sm cursor-pointer",
                  deck.id === activeDeckId
                    ? "bg-neutral-900 text-white dark:bg-white dark:text-neutral-900"
                    : "hover:bg-neutral-100 dark:hover:bg-neutral-800",
                ].join(" ")}
                onClick={() => {
                  setActiveDeckId(deck.id);
                  setMode("flashcards");
                }}
              >
                <span className="truncate">{deck.title}</span>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    handleDelete(deck.id);
                  }}
                  className="ml-2 opacity-0 group-hover:opacity-100"
                  aria-label={`Delete ${deck.title}`}
                >
                  ×
                </button>
              </div>
            ))}
          </aside>

          <main>
            {!activeDeck ? (
              <p className="text-sm text-neutral-400">
                Generate a deck or select one from the list to study.
              </p>
            ) : (
              <div className="flex flex-col gap-6">
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-medium">{activeDeck.title}</h2>
                  <div className="flex gap-2 rounded-md border border-neutral-200 p-1 text-sm dark:border-neutral-700">
                    <button
                      onClick={() => setMode("flashcards")}
                      className={[
                        "rounded px-3 py-1",
                        mode === "flashcards"
                          ? "bg-neutral-900 text-white dark:bg-white dark:text-neutral-900"
                          : "",
                      ].join(" ")}
                    >
                      Flashcards
                    </button>
                    <button
                      onClick={() => setMode("quiz")}
                      className={[
                        "rounded px-3 py-1",
                        mode === "quiz"
                          ? "bg-neutral-900 text-white dark:bg-white dark:text-neutral-900"
                          : "",
                      ].join(" ")}
                    >
                      Quiz
                    </button>
                  </div>
                </div>

                {mode === "flashcards" ? (
                  <FlashcardViewer cards={activeDeck.flashcards} />
                ) : (
                  <QuizMode questions={activeDeck.quiz} />
                )}
              </div>
            )}
          </main>
        </div>
      </div>
    </div>
  );
}
